### ISSUE TITLE
why ?

### ISSUE THREAD

**Issue by eviltik** [meistudioli/msc-image-uploader#3]
hidden picture in your code ? but why ? :)

https://github.com/meistudioli/msc-image-uploader/blob/f54ad799fcd8d79a581beb3c795127728dc1babe/mjs/wc-msc-image-uploader.js#L302

**Comment by meistudioli** [comment]
Hi, evitik:

This node is for drag / drop to change image position's decoy. The image source will change when mouse down. Maybe I should change it to blank image better. Thanks.

**Comment by eviltik** [comment]
Thank you ! :)
